GraphBLAS/python-suitesparse-graphblas

- .github/workflows/test.yml
- README.md
- continuous_integration/environment.yml
- pyproject.toml
- setup.py
- suitesparse_graphblas/build.py
- suitesparse_graphblas/create_headers.py
- suitesparse_graphblas/tests/test_initialize.py
- suitesparse_graphblas/tests/test_package.py
Also, let's require Cython when building (for now).  This is probably safest for now (i.e., less error prone).
Someday, somebody may want to be able to install from source w/o Cython using only .c files.
> Try adding a simple CI script for GithubActions.

- continuous_integration/environment.yml
- suitesparse_graphblas/create_headers.py
- suitesparse_graphblas/suitesparse_graphblas.h
- suitesparse_graphblas/suitesparse_graphblas_no_complex.h
Also, add sanity check to make sure all GrB and GxB lines are handled.
This would have caught the issue of the new functions not being public in v5.0.2.
This is actually a pretty nice way to see the changes between versions!
The conda-forge build for SuiteSparse:GraphBLAS v5.0.3 is in progress.
> Update to SuiteSparse:GraphBLAS 5.0.3.

- pyproject.toml
- setup.py
- suitesparse_graphblas/suitesparse_graphblas.h
- suitesparse_graphblas/suitesparse_graphblas_no_complex.h
Also, update minimum numpy version to 1.17 as per [NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html).
> Update to SuiteSparse:GraphBLAS 5.1.2

- .github/workflows/wheels.yml
- suitesparse.sh
- suitesparse_graphblas/io/binary.py
This fixes a Bad Address problem Tim found saving large matrices.
> Bad address on large iso

- suitesparse.sh
It matched `5.1.1` instead of `5.1.10` here:
https://github.com/GraphBLAS/python-suitesparse-graphblas/runs/4052889018?check_suite_focus=true#step:4:30
> Fix version regex when building wheels

- .github/workflows/test.yml
- setup.py
Instead, I added an easy way to add meaningless commits, which can be helpful to avoid issues with having multiple git tags and releases point to the same git hash.
> Update to v6.2.3.  No code changes needed.

- suitesparse_graphblas/utils.pxd
- suitesparse_graphblas/utils.pyx
Perhaps we should try using `PyArray_NewFromDescr` directly.
I tested this locally on UDTs, and will test this in `grblas` CI.
> Update Cython code to support UDTs

- .github/workflows/test.yml
- suitesparse_graphblas/__init__.py
- suitesparse_graphblas/tests/test_scalar.py
- suitesparse_graphblas/utils.pxd
- suitesparse_graphblas/utils.pyx
Fixes #40 (probably)
Also, run tests randomly to ensure robustness.
Also, I think I forgot an incref in a previous PR, so I'm adding now.  It's possible not having this would result in _other_ mysterious segfaults when using user-defined types.
> Fix issue with `Scalar_setElement_FC64` with cffi voodoo magic

- suitesparse_graphblas/__init__.py
Adds `enable_burble` and `disable_burble`.  I want approval before merging this.  Heh, I couldn't help myself: `burbling` is too fun a name to pass up!
We could also have this as e.g.
```python
>>> from suitesparse_graphblas import burble
>>> burble.enable()
>>> # Do stuff
>>> burble.disable()
>>> with burble:
...     # Do some more stuff
```
Is it worth it as a context manager?  Should it _restore_ to the previous value or GxB_BURBLE instead of disabling it?
> Add helper functions to enable and disable BURBLE to print diagnostics.

- .github/workflows/test.yml
- suitesparse_graphblas/__init__.py
- suitesparse_graphblas/io/serialize.py
- suitesparse_graphblas/matrix.py
- suitesparse_graphblas/suitesparse_graphblas.h
- suitesparse_graphblas/suitesparse_graphblas_arm64.h
- suitesparse_graphblas/suitesparse_graphblas_no_complex.h
Create our header files from v740 branch of SuiteSparse:GraphBLAS. See: https://github.com/GraphBLAS/python-suitesparse-graphblas/issues/56#issuecomment-1362425096
This will let us avoid use of C variadic args, which we have difficulty supporting across systems.
> SuiteSparse:GraphBLAS v740 branch

- .gitignore
Otherwise, our version may end up as `dirty` when building wheels.
> Add `*.c` files to `.gitignore` to keep `setuptools_git_versioning` happy

- .github/workflows/wheels.yml
- MANIFEST.in
- pyproject.toml
- suitesparse.sh
In response to the comment here:
https://github.com/GraphBLAS/python-suitesparse-graphblas/pull/66#issuecomment-1423670808
I would like to investigate and understand the issue with running tests as part of cibuildwheel.
> Include tests as a module in the package

- suitesparse_graphblas/create_headers.py
Use of `suitesparse_graphblas_arm64.h` and `suitesparse_graphblas_no_complex.h` was removed in #68 (`build.py` was renamed to `build_graphblas_cffi.py` and the logic for which header to use was changed). We no longer need arm64.h b/c it is now the same as the standard header. I believe this change occurred in #58.
Technically, we don't need to generate and keep `suitesparse_graphblas_no_complex.h` either since complex works on Windows now, but maybe it's okay/safer to keep around?
> We no longer need suitesparse_graphblas_arm64.h

- .github/workflows/wheels.yml
- add_arm_to_libomp_dylib.sh
- suitesparse.sh
Builds Linux aarch64 wheels using cibuildwheel's built in multi-arch support: https://cibuildwheel.readthedocs.io/en/stable/faq/#emulation
Inspired by matplotlib's approach: https://github.com/matplotlib/matplotlib/blob/main/.github/workflows/cibuildwheel.yml
This uses QEMU emulation since GitHub only offers x86 Linux runners. Cross-compilation isn't built into cibuildwheel yet.
Emulation is about 5x slower than native, but is all-inclusive including the libgraphblas build.
More types are disabled (only for aarch64) because otherwise `suitesparse.sh` only achieves about 70% complete in the 6-hour time limit.
cibuildwheel can use the same Linux runner for all Linux architectures. This PR uses a separate runner for aarch64 only. This way aarch64 has the full 6 hours, and also any general …
> Linux aarch64 wheels

- README.md
- build_graphblas_cffi.py
Look for GraphBLAS first in GraphBLAS_ROOT env var, if empty then fallback to current paths.
using `GraphBLAS_ROOT` because that's what CMake expects when building against GraphBLAS in C++.
fixes https://github.com/GraphBLAS/python-suitesparse-graphblas/issues/79
> Support building from source with user-specified GraphBLAS

- .pre-commit-config.yaml
- suitesparse.sh
This should hopefully allow aarch64 wheels to build faster in CI.
As discussed in #81.
> Replace INT8 with BOOL for SUITESPARSE_FAST_BUILD

- .github/workflows/wheels.yml
- suitesparse.sh
Split macOS wheels into separate x86 and arm runners.
This results in wheels that do not include the other architecture in the other wheels.
The universal2 libomp mechanism is retained to keep the arm install name fix in place. When ARM runners are available you can just delete that script and everything should work unchanged.
See https://github.com/GraphBLAS/python-suitesparse-graphblas/issues/81
> Split macos architectures

- .github/workflows/wheels.yml
This is a followup to #87; I'm not sure whether we should run `add_arm_to_libomp_dylib.sh` on macos x86_64, or only arm64. @alugowski, what do you think?
We have a failure on macos x86_64; see #89. If this PR doesn't help, I think I'll release a (probably) broken package to allow us and users to investigate further.
> Run add_arm_to_libomp_dylib.sh only on arm64

- .github/workflows/wheels.yml
This is probably a bad idea. It would be much better to figure out why the test is failing when building wheels 🤷‍♂️
> Skip tests on macos when building wheels.

- .github/workflows/test.yml
- suitesparse.sh
Testing out the new `-DJITINIT=2` compile-time option. See: https://github.com/DrTimothyAldenDavis/GraphBLAS/releases/tag/v8.0.2.beta1
This disables JIT by default, but allows the JIT to run pre-compiled kernels and to be enabled.
> Update to 8.0.2

- .pre-commit-config.yaml
(mostly just to have a different hash to tag as a new release)
> Bump versions in pre-commit

- .flake8
- .github/workflows/test.yml
- .pre-commit-config.yaml
> Update to 8.2.0

- .github/workflows/test.yml
- .github/workflows/wheels.yml
- pyproject.toml
The Python 3.12 on Linux wheel build process appears to need an additional libffi install. The cibuildwheel docs just happen to use `yum install -y libffi-devel` as an example, and that works well to solve the issue.
This makes Python 3.12 wheels work on all three platforms supported by cibuildwheel (macOS and Windows worked already).
See example run: https://github.com/alugowski/python-suitesparse-graphblas/actions/runs/6388570568/job/17338631246
(The PyPy 3.9 fails are fixed by #100)
> Fix Linux Python 3.12 wheel build

- .github/workflows/wheels.yml
- pyproject.toml
Make PyPy wheels work.
* Fix PyPy 3.9 build by following [SciPy's approach](https://github.com/scipy/scipy/blob/main/pyproject.toml). `oldest-supported-numpy` only works for CPython. That same version is unsupported on PyPy. SciPy uses an unpinned numpy version on PyPy  so pip will download a working version.
* Skip PyPy 3.10 because numpy does not support it.
* PyPy 3.8 works by building numpy from source. Since it works, let it be.
Example Actions run (only PyPy enabled in this special run, with a hacked SS version hence why only macOS succeeds): https://github.com/alugowski/python-suitesparse-graphblas/actions/runs/6388091525/job/17337388925
> Make PyPy wheels work

- .github/workflows/wheels.yml
Tests now pass on cibuildwheel macOS CPython 3.8 through 3.12 and PyPy 3.8. PyPy 3.9 fails, but that's due to an unrelated PyPy build issue fixed by #100.
See example run:
https://github.com/alugowski/python-suitesparse-graphblas/actions/runs/6388465933/job/17338344935
Closes #89
> Re-enable testing macOS wheels

- .github/workflows/test.yml
I think Python 3.12 is available from conda-forge now (if not, we'll keep this as a PR until it is).
> Test Python 3.12 in CI

- .github/workflows/wheels.yml
- suitesparse.sh
This PR aims to improve the stability of wheels by:
* Run the build wheels workflow on every PR and push to `main`, as if it was a unit test. This helps identify breaking changes early.
* Switch cibuildwheel to use their github action, whose version is managed by dependabot. This helps identify any problems caused by new cibuildwheel versions because any updates become dependabot PRs which run the wheels workflow.
`wheels.yml` is configured to run on push to main and on PR. To make this sane, a new `SUITESPARSE_FASTEST_BUILD` option to `suitesparse.sh` is added that omits every optional compilation feature I know to make the build as fast as possible. Feel free to suggest more. Building GraphBLAS in CI seems to take 5-10 minutes in this configuration. The emulated `aarch64` obviously sill …
> Run wheels workflow on PR and cibuildwheel github action

- .github/workflows/test.yml
- .github/workflows/wheels.yml
- add_arm_to_libomp_dylib.sh
Also, hopefully fix #109 by changing release trigger to "published", not "created".
> Update to SuiteSparse:GraphBLAS 8.2.1

- .github/workflows/wheels.yml
Add an input to manual dispatch of the wheel workflow:
Choose between skipping wheel upload, or upload to PyPI or Test PyPI.
Useful if a release run fails for an ephemeral reason and just needs a retry. Just trigger the workflow and specify upload to PyPI.
Also this makes it easier to use Test PyPI for things that don't need to be pushed publicly. This could be testing changes to the PyPI upload process itself, or experiments that shouldn't be public.
> Add an upload destination input to wheels workflow manual dispatch

- .github/workflows/wheels.yml
Resolve this error when uploading to PyPI using trusted publishing mechanism:
> Trusted publishing exchange failure: 
OpenID Connect token retrieval failed: GitHub: missing or insufficient OIDC token permissions, the ACTIONS_ID_TOKEN_REQUEST_TOKEN environment variable was unset
> 
> This generally indicates a workflow configuration error, such as insufficient
permissions. Make sure that your workflow has `id-token: write` configured
at the job level, e.g.:
> 
> ```yaml
> permissions:
>   id-token: write
> ```
> Add id-token permission for PyPI trusted publishing

- add_arm_to_libomp_dylib.sh
Monterey is now the oldest supported macOS.
> Move libomp script to monterey

- .github/workflows/wheels.yml
Main incompatible change between v3 and v4 is that artifacts are immutable once created.
The old v3 workflow, as recommended by the PyPI docs, would have each runner append to a common artifact. That no longer works. Instead properly name each artifact (sdist, wheels for each platform) so there are no name conflicts. The download-artifact action now downloads each artifact into its own directory, so these are flattened for the pypi action.
> Bump actions/upload-artifact and download-artifact from 3 to 4

- .github/workflows/wheels.yml
Version 4.1 of `download-artifact` action was released today that includes a `merge-multiple` input. This makes the manual flatten step redundant.
> Simplify download-artifact usage thanks to v4.1 `merge-multiple` input

- .github/workflows/wheels.yml
> Move from macos-12 to macos-13 runner
